(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "auto-complete" :git "https://github.com/auto-complete/auto-complete.git")
(depends-on "helm" :git "https://github.com/emacs-helm/helm.git")
(depends-on "web-mode" :git "https://github.com/fxbois/web-mode.git")
(depends-on "js2-mode" :git "https://github.com/mooz/js2-mode.git")
(depends-on "php-mode" :git "https://github.com/ejmr/php-mode.git")
(depends-on "php-completion" :git "https://github.com/suzuki/php-completion.git")
(depends-on "php-auto-yasnippets" :git "https://github.com/ejmr/php-auto-yasnippets.git")
(depends-on "yasnippet" :git "https://github.com/capitaomorte/yasnippet.git")
(depends-on "init-open-recentf" :git "https://github.com/zonuexe/init-open-recentf.el.git")
(depends-on "highlight-indentation" :git "https://github.com/antonj/Highlight-Indentation-for-Emacs.git")
(depends-on "rinari" :git "git://github.com/eschulte/rinari.git")
(depends-on "scss-mode" :git "https://github.com/antonj/scss-mode.git")